connection:
  mysql:
    enabled: false
    address: "localhost:3306"
    username: "root"
    passowrd: ""
    database: "test"
  sqlite:
    file: "market.sql"

announcement:
  message: "&2&lMERCADO &7%player%&f anunciou um item por &a%amount%"
  # Para evitar floods de anúncios, a cada 10 minutos (600 segundos), o jogador terá, ao anunciar um
  # novo item, um novo anúncio, do contrário, o item será anunciado sem destaque.
  delay: 600
  # Preço por anúncio (-1 para desativar)
  price: -1
  # Tempo pro item se expirar (em segundos)
  expire-time: 3600
  # Valor mínimo para colocar itens no mercado (Não colocar valores menores que 1 :d)
  minimum-value: 100
  # Valor máximo para colocar itens no mercado (-1 para desativar)
  maximum-value: -1

command-message:
  - '&2&lMERCADO &f- Ajuda'
  - ''
  - '&a/mercado &7- Exibe essa mensagem.'
  - '&a/mercado ver &7- Abra o mercado.'
  - '&a/mercado vender <valor> &7- Venda o item que está segurando.'
  - '&a/mercado vender <valor> (jogador) &7- Venda o item para um jogador em específico.'
  - '&a/mercado expirados &7- Veja seus itens que foram expirados e removidos do mercado.'
  - '&a/mercado anunciados &7- Veja seus itens anunciados.'
  - ''

messages:
  maximum-value-reached: '&cVocê inseriu um valor muito alto.'
  minimum-value-not-reached: '&cVocê precisa por um valor acima de %amount%.'
  player-offline: '&cEste jogador encontra-se offline.'
  expired-item: '&cUm item seu expirou no mercado, use &f/mercado expirados&c para coletar.'
  bought-a-item: '&aVocê comprou um item do mercado.'
  sold-a-item: '&aVocê vendeu um item por &f%amount% &ano mercado.'
  announced-a-item: '&aVocê anunciou um item por &f%amount% &ano mercado.'
  announced-a-item-in-personal-market: '&aVocê anunciou um item por &f%amount% &ano mercado pessoal de &f%player%&a.'
  insufficient-money: '&cVocê não tem dinheiro suficiente para comprar este item :(.'
  invalid-item: '&cEste item não pertence a nenhuma categoria.'
