connection:
  mysql:
    enable: false
    address: "localhost:3306"
    username: "root"
    password: ""
    database: "test"
  sqlite:
    file: "market.sql"

features:
  # bStats é usado apenas para os desenvolvedores terem uma noção de quantas pessoas usam o plugin
  useBStats: true

announcement:
  # Enviar mensagem de aviso sobre novos anúncios no mercado (pessoal e global)
  message: true
  # Para evitar floods de anúncios, a cada 10 minutos (600 segundos), o jogador terá, ao anunciar um
  # novo item, um novo anúncio, do contrário, o item será anunciado sem destaque.
  delay: 600
  # Tempo pro item se expirar (em segundos)
  expire-time: 3600
  # Valor mínimo para colocar itens no mercado (Não colocar valores menores que 1 :d)
  minimum-value: 100
  # Valor máximo para colocar itens no mercado (-1 para desativar). Atenção: O formatador só vai até 1E72 (QTV), em breve será aumentado
  maximum-value: 1E72

limits: # Limite de itens de um mesmo jogador no mercado (para poder anunciar itens, é preciso ter pelo menos uma delas)
  # Limite para membros comuns (não precisa de permissão de limites, apenas a permissão para usar os comandos)
  default: 3
  # Limite para o jogador com a permissão 'nextmarket.limit.vip1'
  vip1: 5
  # Limite para o jogador com a permissão 'nextmarket.limit.vip2'
  vip2: 7
  # Limite para o jogador com a permissão 'nextmarket.limit.vip3'
  vip3: 9

messages:
  command-message:
    - '&2&lMERCADO &f- Ajuda'
    - ''
    - '&a/mercado ver &7- Abra o menu de categorias do mercado.'
    - '&a/mercado vender <valor> [jogador]&7- Coloque o item de sua mão a venda.'
    - '&a/mercado pessoal &7- Veja os itens que foram anunciados especialmente para você.'
    - '&a/mercado anunciados &7- Veja seus itens anunciados e expirados.'
    - ''
  maximum-value-reached: '&cVocê inseriu um valor muito alto.'
  minimum-value-not-reached: '&cVocê precisa por um valor acima de %amount%.'
  no-permission: '&cVocê não tem permissão para anunciar um item no mercado.'
  out-of-bounds: '&cVocê atingiu o limite de %limit% items no mercado!'
  player-offline: '&cEste jogador encontra-se offline.'
  cancel-a-sell: '&cVocê cancelou a venda deste item!'
  collect-product: '&aVocê recolheu um produto que estava expirado!'
  expired-item: '&cUm item seu expirou no mercado, use &f/mercado expirados&c para coletar.'
  bought-a-item: '&aVocê comprou um item do mercado.'
  sold-a-item: '&aVocê vendeu um item por &f%amount% &ano mercado.'
  selling-a-item: '&aVocê anunciou um item por &f%price% &ano mercado.'
  selling-a-item-in-personal-market: '&aVocê anunciou um item por &f%price% &ano mercado pessoal de &f%player%&a.'
  insufficient-money: '&cVocê precisa de mais %difference% para comprar este item.'
  invalid-item: '&cEste item não pertence a nenhuma categoria.'
  invalid-number: '&cInsira apenas números válidos.'
  full-inventory: '&cSeu inventário está cheio, cancelando operação!'
  selling-for-you: '&cVocê não pode vender um item para você mesmo!'
  category-not-exists: "&cOps, me parece que esta categoria não existe!"
  unavailable-product: "&COps, me parece que este produto não está mais disponível!"
  announcement: "&2&lMERCADO &7%player%&f anunciou um item por &a%price%!"
  private-announcement: "&2&lMERCADO &7%player%&f colocou um item em seu mercado pessoal!"
  changed-hand-item: "&cVocê mudou o item de sua mão em quando estava confirmando a ação, por favor, refaça a operação!"
  correct-usage-sell: "&cUse /mercado vender <valor> [jogador]!"
